*** Variables ***
${R_SFTP_HOST}    ${CONFIG_SFTP_HOST}
${R_SFTP_USERNAME}    ${CONFIG_SFTP_USERNAME}
${R_SFTP_PWD}     ${CONFIG_SFTP_PWD}
${R_SFTP_ITEM_PATH_NS_1}    ${CONFIG_SFTP_ITEM_PATH_NS_1}
${R_SFTP_ITEM_PATH_NS_2}    ${CONFIG_SFTP_ITEM_PATH_NS_2}
${R_SFTP_ITEM_PATH_NS_3}    ${CONFIG_SFTP_ITEM_PATH_NS_3}
${R_SFTP_ITEM_PATH_NS_4}    ${CONFIG_SFTP_ITEM_PATH_NS_4}
${R_SFTP_ITEM_PATH_NS_5}    ${CONFIG_SFTP_ITEM_PATH_NS_5}
${R_SFTP_ITEM_PATH_NS_6}    ${CONFIG_SFTP_ITEM_PATH_NS_6}
${R_SFTP_ITEM_PATH_SC_1}    ${CONFIG_SFTP_ITEM_PATH_SC_1}
${R_SFTP_PO_PATH_NS_1}    ${CONFIG_SFTP_PO_PATH_NS_1}
${R_SFTP_PO_PATH_NS_2}    ${CONFIG_SFTP_PO_PATH_NS_2}
${R_SFTP_PO_PATH_NS_3}    ${CONFIG_SFTP_PO_PATH_NS_3}
${R_SFTP_PO_PATH_NS_4}    ${CONFIG_SFTP_PO_PATH_NS_4}
${R_SFTP_PO_PATH_NS_5}    ${CONFIG_SFTP_PO_PATH_NS_5}
${R_SFTP_PO_PATH_NS_6}    ${CONFIG_SFTP_PO_PATH_NS_6}
${R_SFTP_PO_PATH_SC_1}    ${CONFIG_SFTP_PO_PATH_SC_1}
