*** Variables ***
${R_SUPPLIER_NS_1}    ${CONFIG_SUPPLIER_NS_1}
${R_SUPPLIER_NS_2}    ${CONFIG_SUPPLIER_NS_2}
${R_SUPPLIER_NS_3}    ${CONFIG_SUPPLIER_NS_3}
${R_SUPPLIER_NS_4}    ${CONFIG_SUPPLIER_NS_4}
${R_SUPPLIER_NS_5}    ${CONFIG_SUPPLIER_NS_5}
${R_SUPPLIER_NS_6}    ${CONFIG_SUPPLIER_NS_6}
${R_SUPPLIER_SC_1}    ${CONFIG_SUPPLIER_SC_1}
${R_SUPPLIER_NS_1_KEY}    ${CONFIG_SUPPLIER_NS_1_KEY}
${R_SUPPLIER_NS_2_KEY}    ${CONFIG_SUPPLIER_NS_2_KEY}
${R_SUPPLIER_NS_3_KEY}    ${CONFIG_SUPPLIER_NS_3_KEY}
${R_SUPPLIER_NS_4_KEY}    ${CONFIG_SUPPLIER_NS_4_KEY}
${R_SUPPLIER_NS_5_KEY}    ${CONFIG_SUPPLIER_NS_5_KEY}
${R_SUPPLIER_NS_6_KEY}    ${CONFIG_SUPPLIER_NS_6_KEY}
${R_SUPPLIER_SC_1_KEY}    ${CONFIG_SUPPLIER_SC_1_KEY}
