*** Variables ***
${R_TEST_DATA_ITEM}    test_suite/item_master/test_data/
${R_TEST_DATA_ITEM_GENERATE}    test_suite/item_master/test_data/generate/
${R_TEST_DATA_SUPPLIER}    test_suite/supplier/test_data/
${R_TEST_DATA_SUPPLIER_GENERATE}    test_suite/supplier/test_data/generate/
${R_TEST_DATA_PO}    test_suite/purchase_order/test_data/
${R_TEST_DATA_PO_GENERATE}    test_suite/purchase_order/test_data/generate/
${R_TEST_DATA_SO}    test_suite/sale_order/test_data/
${R_TEST_DATA_INV}    test_suite/inventory/test_data/
${R_TEST_DATA_SO}    test_suite/sale_order/test_data/
${R_TEMPLATE_ITEM_OVER_UPC}    ${R_TEST_DATA_ITEM}json/template_item_over_upc.json
${R_TEMPLATE_ITEM_WITH_ALL_FIELD_CSV}    ${R_TEST_DATA_ITEM}csv/create_item_all_field.csv
${R_TEMPLATE_TWO_ITEMS_WITH_ALL_FIELD_CSV}    ${R_TEST_DATA_ITEM}csv/create_two_items_with_all_field.csv
${R_TEMPLATE_THREE_ITEMS_WITH_ALL_FIELD_CSV}    ${R_TEST_DATA_ITEM}csv/create_three_items_with_all_field.csv
${R_TEMPLATE_ITEM_MANDA_AND_REQUIRE_FIELD_CSV}    ${R_TEST_DATA_ITEM}csv/create_item_manda_and_require_field.csv
${R_TEMPLATE_ITEM_MANDA_AND_NO_REQUIRE_FIELD_CSV}    ${R_TEST_DATA_ITEM}csv/create_item_manda_and_no_require_field.csv
${R_TEMPLATE_ITEM_MANDA_AND_REQUIRE_FIELD_AND_EMPTY_CSV}    ${R_TEST_DATA_ITEM}csv/create_item_with_req_field_and_empty_line.csv
${R_TEMPLATE_ITEM}    ${R_TEST_DATA_ITEM}json/template_item.json
${R_TEMPLATE_DEL_ITEM}    ${R_TEST_DATA_ITEM}json/template_del_item.json
${R_TEMPLATE_ITEM_SERVICE_DISCOUNT_ONE_ITEM}   ${R_TEST_DATA_ITEM}json/template_item_service_discount.json
${R_TEMPLATE_SUPPLIER}    ${R_TEST_DATA_SUPPLIER}json/create_supplier_all_field.json
${R_TEMPLATE_SUPPLIER_FALSE_CSV}    ${R_TEST_DATA_SUPPLIER}csv/create_supplier_false.csv
${R_TEMPLATE_PO_ONE_ITEM}    ${R_TEST_DATA_PO}json/template_po_one_item.json
${R_TEMPLATE_PO_TWO_ITEM}    ${R_TEST_DATA_PO}json/template_po_two_item.json
${R_TEMPLATE_PO_THREE_ITEM}    ${R_TEST_DATA_PO}json/template_po_three_item.json
${R_TEMPLATE_PO_FOUR_ITEM}    ${R_TEST_DATA_PO}json/template_po_four_item.json
${R_TEMPLATE_PO_WITH_ALL_FIELD_CSV}    ${R_TEST_DATA_PO}csv/create_po_all_field.csv
${R_TEMPLATE_GRN_ONE_ITEM}    ${R_TEST_DATA_PO}xml/template_grn_one_item.xml
${R_TEMPLATE_GRN_TWO_ITEM_ONE_CONTAINERS}    ${R_TEST_DATA_PO}xml/template_grn_two_item_one_containers.xml
${R_TEMPLATE_GRN_FOUR_ITEM_ONE_CONTAINERS}    ${R_TEST_DATA_PO}xml/template_grn_four_item_one_containers.xml
${R_TEMPLATE_GRN_TWO_ITEM_TWO_CONTAINERS}    ${R_TEST_DATA_PO}xml/template_grn_two_item_two_containers.xml
${R_TEMPLATE_PUTAWAY_ONE_ITEM}    ${R_TEST_DATA_PO}xml/template_putaway_one_item.xml
${R_TEMPLATE_SO_ONE_ITEM_ONE_LINE_NO_SERIAL}    ${R_TEST_DATA_SO}json/create_so.json
${R_TEMPLATE_SO_TWO_PRODUCT}    ${R_TEST_DATA_SO}json/create_so_with_2_product.json
${R_TEMPLATE_SO_TWO_PRODUCT_TWO_ITEM}    ${R_TEST_DATA_SO}json/create_so_with_2_product_2_item.json
${R_TEMPLATE_CANCEL_SUCCESS}    ${R_TEST_DATA_SO}json/cancel_success_from_scale.json
${R_TEMPLATE_CANCEL_FAIL}    ${R_TEST_DATA_SO}json/cancel_fail_from_scale.json
${R_TEMPLATE_PICKING_PENDING}    ${R_TEST_DATA_SO}xml/picking_pending.xml
${R_TEMPLATE_ORDER_CONFIRM}    ${R_TEST_DATA_SO}xml/order_confirm.xml
${R_TEMPLATE_ORDER_CONFIRM_WITH_3_SN}    ${R_TEST_DATA_SO}xml/order_confirm_one_item_three_serial.xml
${R_TEMPLATE_ORDER_CONFIRM_TWO_ITEM}    ${R_TEST_DATA_SO}xml/order_confirm_two_item.xml
${R_TEMPLATE_CANCEL_REASON}    ${R_TEST_DATA_SO}json/cancel_reason.json
${R_TEMPLATE_ORDER_CONFIRM_TWO_PRODUCT}    ${R_TEST_DATA_SO}xml/order_confirm_two_product.xml
${R_TEMPLATE_ADJ_AVI_LOCATION_MOVE}    ${R_TEST_DATA_INV}xml/adj_avai_location_move.xml
${R_TEMPLATE_ADJ_ONHAND_POSITIVE}    ${R_TEST_DATA_INV}xml/adj_onh_positive.xml
${R_TEMPLATE_ADJ_ONHAND_NEGATIVE}    ${R_TEST_DATA_INV}xml/adj_onh_negative.xml
${R_TEMPLATE_ADJ_ONHAND_CYCLECOUNT}    ${R_TEST_DATA_INV}xml/adj_onh_cyclecount.xml
### Sales Order template
${R_TEMPLATE_ITEM_MASTER}                  ${R_TEST_DATA_SO}json/item_master_template.json
${R_TEMPLATE_SO_SINGLE_LINE_SINGLE_ITEM}   ${R_TEST_DATA_SO}json/single_line_single_item.json
${R_TEMPLATE_SCALE_PO_GRN_ONE_ITEM}        ${R_TEST_DATA_SO}/xml/po_grn_one_item.xml
${R_TEMPLATE_SCALE_PO_PUT_AWAY_ONE_ITEM}   ${R_TEST_DATA_SO}/xml/po_putaway_one_item.xml
${R_TEMPLATE_SCALE_PICKING_PENDING_ONE_ITEM}   ${R_TEST_DATA_SO}/xml/picking_pending.xml
${R_TEMPLATE_SCALE_ORDER_CONFIRM_ONE_ITEM}   ${R_TEST_DATA_SO}/xml/order_confirm_one_item_three_serial.xml
### Sales Order - Non GL template
${R_TEMPLATE_SO_NON_GL_CUSTOMER_INFO}                  ${R_TEST_DATA_SO}json/Non-GL/update_customerInfo.json
${R_TEMPLATE_SO_NON_GL_ORDER_SHIPMENT_INFO}            ${R_TEST_DATA_SO}json/Non-GL/update_orderShipmentInfo.json
${R_TEMPLATE_SO_NON_GL_ORDER_BILLING_INFO}             ${R_TEST_DATA_SO}json/Non-GL/update_orderBillingInfo.json
${R_TEMPLATE_SO_NON_GL_SHIPPING_TYPE}                  ${R_TEST_DATA_SO}json/Non-GL/update_shippingType.json
${R_TEMPLATE_SO_NON_GL_ALL}                            ${R_TEST_DATA_SO}json/Non-GL/update_all_non_gl.json
