*** Variables ***
${R_WAREHOUSE_CODE_NS1}    ${CONFIG_WAREHOUSE_CODE_NS1}
${R_WAREHOUSE_CODE_NS2}    ${CONFIG_WAREHOUSE_CODE_NS2}
${R_WAREHOUSE_CODE_SC1}    ${CONFIG_WAREHOUSE_CODE_SC1}
${R_WAREHOUSE_CODE_LAS}    ${CONFIG_WAREHOUSE_CODE_LAS}
${R_WAREHOUSE_CODE_RM3}    ${CONFIG_WAREHOUSE_CODE_RM3}
${R_WAREHOUSE_CODE_BNG}    ${CONFIG_WAREHOUSE_CODE_BNG}
